[package]
name = "dam"
version = "0.1.0"
edition = "2024"
description = "ダムの貯水率を表示するアプリ"

[dependencies]
clap ={ version = "4.5.4", features = ["derive"]}
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
scraper = "0.23.1"
regex = "1"